moduloclientes_cliente_homeClientes:
    pattern:  /homeClientes
    defaults: { _controller: moduloclientesclienteBundle:Home:homeClientes }
moduloclientes_cliente_canchasClientes:
    pattern:  /canchasClientes
    defaults: { _controller: moduloclientesclienteBundle:Cancha:canchasClientes }
moduloclientes_cliente_canchaClientes:
    pattern:  /canchaClientes/{matricula}
    defaults: { _controller: moduloclientesclienteBundle:Cancha:canchaClientes }
moduloclientes_cliente_reservasClientes:
    pattern:  /reservasClientes
    defaults: { _controller: moduloclientesclienteBundle:Reserva:reservasClientes }
moduloclientes_cliente_reservaClientes:
    pattern:  /reservaClientes/{matricula}
    defaults: { _controller: moduloclientesclienteBundle:Reserva:reservaClientes }
moduloclientes_cliente_torneosClientes:
    pattern:  /torneosClientes
    defaults: { _controller: moduloclientesclienteBundle:Torneo:torneosClientes }
moduloclientes_cliente_torneoClientes:
    pattern:  /torneoClientes/{matricula}
    defaults: { _controller: moduloclientesclienteBundle:Torneo:torneoClientes }
moduloclientes_cliente_sesionesClientes:
    pattern:  /sesionesClientes
    defaults: { _controller: moduloclientesclienteBundle:Sesion:sesionesClientes }
moduloclientes_cliente_sesionClientes:
    pattern:  /sesionClientes/{matricula}
    defaults: { _controller: moduloclientesclienteBundle:Sesion:sesionClientes }